// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: _portfolio_rpc.proto

/*
Package _portfolio_rpcpb is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package _portfolio_rpcpb

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

func request_HeliosPortfolioRPC_AccountPortfolio_0(ctx context.Context, marshaler runtime.Marshaler, client HeliosPortfolioRPCClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq AccountPortfolioRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.AccountPortfolio(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_HeliosPortfolioRPC_AccountPortfolio_0(ctx context.Context, marshaler runtime.Marshaler, server HeliosPortfolioRPCServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq AccountPortfolioRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.AccountPortfolio(ctx, &protoReq)
	return msg, metadata, err

}

func request_HeliosPortfolioRPC_AccountPortfolioBalances_0(ctx context.Context, marshaler runtime.Marshaler, client HeliosPortfolioRPCClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq AccountPortfolioBalancesRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.AccountPortfolioBalances(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_HeliosPortfolioRPC_AccountPortfolioBalances_0(ctx context.Context, marshaler runtime.Marshaler, server HeliosPortfolioRPCServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq AccountPortfolioBalancesRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.AccountPortfolioBalances(ctx, &protoReq)
	return msg, metadata, err

}

func request_HeliosPortfolioRPC_StreamAccountPortfolio_0(ctx context.Context, marshaler runtime.Marshaler, client HeliosPortfolioRPCClient, req *http.Request, pathParams map[string]string) (HeliosPortfolioRPC_StreamAccountPortfolioClient, runtime.ServerMetadata, error) {
	var protoReq StreamAccountPortfolioRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	stream, err := client.StreamAccountPortfolio(ctx, &protoReq)
	if err != nil {
		return nil, metadata, err
	}
	header, err := stream.Header()
	if err != nil {
		return nil, metadata, err
	}
	metadata.HeaderMD = header
	return stream, metadata, nil

}

// RegisterHeliosPortfolioRPCHandlerServer registers the http handlers for service HeliosPortfolioRPC to "mux".
// UnaryRPC     :call HeliosPortfolioRPCServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterHeliosPortfolioRPCHandlerFromEndpoint instead.
func RegisterHeliosPortfolioRPCHandlerServer(ctx context.Context, mux *runtime.ServeMux, server HeliosPortfolioRPCServer) error {

	mux.Handle("POST", pattern_HeliosPortfolioRPC_AccountPortfolio_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/_portfolio_rpc.HeliosPortfolioRPC/AccountPortfolio", runtime.WithHTTPPathPattern("/_portfolio_rpc.HeliosPortfolioRPC/AccountPortfolio"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_HeliosPortfolioRPC_AccountPortfolio_0(rctx, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HeliosPortfolioRPC_AccountPortfolio_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("POST", pattern_HeliosPortfolioRPC_AccountPortfolioBalances_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/_portfolio_rpc.HeliosPortfolioRPC/AccountPortfolioBalances", runtime.WithHTTPPathPattern("/_portfolio_rpc.HeliosPortfolioRPC/AccountPortfolioBalances"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_HeliosPortfolioRPC_AccountPortfolioBalances_0(rctx, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HeliosPortfolioRPC_AccountPortfolioBalances_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("POST", pattern_HeliosPortfolioRPC_StreamAccountPortfolio_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		err := status.Error(codes.Unimplemented, "streaming calls are not yet supported in the in-process transport")
		_, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
		return
	})

	return nil
}

// RegisterHeliosPortfolioRPCHandlerFromEndpoint is same as RegisterHeliosPortfolioRPCHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterHeliosPortfolioRPCHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterHeliosPortfolioRPCHandler(ctx, mux, conn)
}

// RegisterHeliosPortfolioRPCHandler registers the http handlers for service HeliosPortfolioRPC to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterHeliosPortfolioRPCHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterHeliosPortfolioRPCHandlerClient(ctx, mux, NewHeliosPortfolioRPCClient(conn))
}

// RegisterHeliosPortfolioRPCHandlerClient registers the http handlers for service HeliosPortfolioRPC
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "HeliosPortfolioRPCClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "HeliosPortfolioRPCClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "HeliosPortfolioRPCClient" to call the correct interceptors.
func RegisterHeliosPortfolioRPCHandlerClient(ctx context.Context, mux *runtime.ServeMux, client HeliosPortfolioRPCClient) error {

	mux.Handle("POST", pattern_HeliosPortfolioRPC_AccountPortfolio_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req, "/_portfolio_rpc.HeliosPortfolioRPC/AccountPortfolio", runtime.WithHTTPPathPattern("/_portfolio_rpc.HeliosPortfolioRPC/AccountPortfolio"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_HeliosPortfolioRPC_AccountPortfolio_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HeliosPortfolioRPC_AccountPortfolio_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("POST", pattern_HeliosPortfolioRPC_AccountPortfolioBalances_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req, "/_portfolio_rpc.HeliosPortfolioRPC/AccountPortfolioBalances", runtime.WithHTTPPathPattern("/_portfolio_rpc.HeliosPortfolioRPC/AccountPortfolioBalances"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_HeliosPortfolioRPC_AccountPortfolioBalances_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HeliosPortfolioRPC_AccountPortfolioBalances_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("POST", pattern_HeliosPortfolioRPC_StreamAccountPortfolio_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req, "/_portfolio_rpc.HeliosPortfolioRPC/StreamAccountPortfolio", runtime.WithHTTPPathPattern("/_portfolio_rpc.HeliosPortfolioRPC/StreamAccountPortfolio"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_HeliosPortfolioRPC_StreamAccountPortfolio_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HeliosPortfolioRPC_StreamAccountPortfolio_0(ctx, mux, outboundMarshaler, w, req, func() (proto.Message, error) { return resp.Recv() }, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_HeliosPortfolioRPC_AccountPortfolio_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"_portfolio_rpc.HeliosPortfolioRPC", "AccountPortfolio"}, ""))

	pattern_HeliosPortfolioRPC_AccountPortfolioBalances_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"_portfolio_rpc.HeliosPortfolioRPC", "AccountPortfolioBalances"}, ""))

	pattern_HeliosPortfolioRPC_StreamAccountPortfolio_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"_portfolio_rpc.HeliosPortfolioRPC", "StreamAccountPortfolio"}, ""))
)

var (
	forward_HeliosPortfolioRPC_AccountPortfolio_0 = runtime.ForwardResponseMessage

	forward_HeliosPortfolioRPC_AccountPortfolioBalances_0 = runtime.ForwardResponseMessage

	forward_HeliosPortfolioRPC_StreamAccountPortfolio_0 = runtime.ForwardResponseStream
)
