// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: helios/hyperion/v1/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Params struct {
	CounterpartyChainParams []*CounterpartyChainParams `protobuf:"bytes,1,rep,name=counterparty_chain_params,json=counterpartyChainParams,proto3" json:"counterparty_chain_params,omitempty"`
	Admins                  []string                   `protobuf:"bytes,2,rep,name=admins,proto3" json:"admins,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5f87689d64baa8c, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetCounterpartyChainParams() []*CounterpartyChainParams {
	if m != nil {
		return m.CounterpartyChainParams
	}
	return nil
}

func (m *Params) GetAdmins() []string {
	if m != nil {
		return m.Admins
	}
	return nil
}

type CounterpartyChainParams struct {
	HyperionId                    string                      `protobuf:"bytes,1,opt,name=hyperion_id,json=hyperionId,proto3" json:"hyperion_id,omitempty"`
	ContractSourceHash            string                      `protobuf:"bytes,2,opt,name=contract_source_hash,json=contractSourceHash,proto3" json:"contract_source_hash,omitempty"`
	BridgeCounterpartyAddress     string                      `protobuf:"bytes,3,opt,name=bridge_counterparty_address,json=bridgeCounterpartyAddress,proto3" json:"bridge_counterparty_address,omitempty"`
	BridgeChainId                 uint64                      `protobuf:"varint,4,opt,name=bridge_chain_id,json=bridgeChainId,proto3" json:"bridge_chain_id,omitempty"`
	SignedValsetsWindow           uint64                      `protobuf:"varint,5,opt,name=signed_valsets_window,json=signedValsetsWindow,proto3" json:"signed_valsets_window,omitempty"`
	SignedBatchesWindow           uint64                      `protobuf:"varint,6,opt,name=signed_batches_window,json=signedBatchesWindow,proto3" json:"signed_batches_window,omitempty"`
	SignedClaimsWindow            uint64                      `protobuf:"varint,7,opt,name=signed_claims_window,json=signedClaimsWindow,proto3" json:"signed_claims_window,omitempty"`
	TargetBatchTimeout            uint64                      `protobuf:"varint,8,opt,name=target_batch_timeout,json=targetBatchTimeout,proto3" json:"target_batch_timeout,omitempty"`
	AverageBlockTime              uint64                      `protobuf:"varint,9,opt,name=average_block_time,json=averageBlockTime,proto3" json:"average_block_time,omitempty"`
	AverageCounterpartyBlockTime  uint64                      `protobuf:"varint,10,opt,name=average_counterparty_block_time,json=averageCounterpartyBlockTime,proto3" json:"average_counterparty_block_time,omitempty"`
	SlashFractionValset           cosmossdk_io_math.LegacyDec `protobuf:"bytes,11,opt,name=slash_fraction_valset,json=slashFractionValset,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"slash_fraction_valset"`
	SlashFractionBatch            cosmossdk_io_math.LegacyDec `protobuf:"bytes,12,opt,name=slash_fraction_batch,json=slashFractionBatch,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"slash_fraction_batch"`
	SlashFractionClaim            cosmossdk_io_math.LegacyDec `protobuf:"bytes,13,opt,name=slash_fraction_claim,json=slashFractionClaim,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"slash_fraction_claim"`
	SlashFractionConflictingClaim cosmossdk_io_math.LegacyDec `protobuf:"bytes,14,opt,name=slash_fraction_conflicting_claim,json=slashFractionConflictingClaim,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"slash_fraction_conflicting_claim"`
	UnbondSlashingValsetsWindow   uint64                      `protobuf:"varint,15,opt,name=unbond_slashing_valsets_window,json=unbondSlashingValsetsWindow,proto3" json:"unbond_slashing_valsets_window,omitempty"`
	SlashFractionBadEthSignature  cosmossdk_io_math.LegacyDec `protobuf:"bytes,16,opt,name=slash_fraction_bad_eth_signature,json=slashFractionBadEthSignature,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"slash_fraction_bad_eth_signature"`
	CosmosCoinDenom               string                      `protobuf:"bytes,17,opt,name=cosmos_coin_denom,json=cosmosCoinDenom,proto3" json:"cosmos_coin_denom,omitempty"`
	CosmosCoinErc20Contract       string                      `protobuf:"bytes,18,opt,name=cosmos_coin_erc20_contract,json=cosmosCoinErc20Contract,proto3" json:"cosmos_coin_erc20_contract,omitempty"`
	ClaimSlashingEnabled          bool                        `protobuf:"varint,19,opt,name=claim_slashing_enabled,json=claimSlashingEnabled,proto3" json:"claim_slashing_enabled,omitempty"`
	BridgeContractStartHeight     uint64                      `protobuf:"varint,20,opt,name=bridge_contract_start_height,json=bridgeContractStartHeight,proto3" json:"bridge_contract_start_height,omitempty"`
	ValsetReward                  types.Coin                  `protobuf:"bytes,21,opt,name=valset_reward,json=valsetReward,proto3" json:"valset_reward"`
}

func (m *CounterpartyChainParams) Reset()         { *m = CounterpartyChainParams{} }
func (m *CounterpartyChainParams) String() string { return proto.CompactTextString(m) }
func (*CounterpartyChainParams) ProtoMessage()    {}
func (*CounterpartyChainParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5f87689d64baa8c, []int{1}
}
func (m *CounterpartyChainParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CounterpartyChainParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CounterpartyChainParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CounterpartyChainParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CounterpartyChainParams.Merge(m, src)
}
func (m *CounterpartyChainParams) XXX_Size() int {
	return m.Size()
}
func (m *CounterpartyChainParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CounterpartyChainParams.DiscardUnknown(m)
}

var xxx_messageInfo_CounterpartyChainParams proto.InternalMessageInfo

func (m *CounterpartyChainParams) GetHyperionId() string {
	if m != nil {
		return m.HyperionId
	}
	return ""
}

func (m *CounterpartyChainParams) GetContractSourceHash() string {
	if m != nil {
		return m.ContractSourceHash
	}
	return ""
}

func (m *CounterpartyChainParams) GetBridgeCounterpartyAddress() string {
	if m != nil {
		return m.BridgeCounterpartyAddress
	}
	return ""
}

func (m *CounterpartyChainParams) GetBridgeChainId() uint64 {
	if m != nil {
		return m.BridgeChainId
	}
	return 0
}

func (m *CounterpartyChainParams) GetSignedValsetsWindow() uint64 {
	if m != nil {
		return m.SignedValsetsWindow
	}
	return 0
}

func (m *CounterpartyChainParams) GetSignedBatchesWindow() uint64 {
	if m != nil {
		return m.SignedBatchesWindow
	}
	return 0
}

func (m *CounterpartyChainParams) GetSignedClaimsWindow() uint64 {
	if m != nil {
		return m.SignedClaimsWindow
	}
	return 0
}

func (m *CounterpartyChainParams) GetTargetBatchTimeout() uint64 {
	if m != nil {
		return m.TargetBatchTimeout
	}
	return 0
}

func (m *CounterpartyChainParams) GetAverageBlockTime() uint64 {
	if m != nil {
		return m.AverageBlockTime
	}
	return 0
}

func (m *CounterpartyChainParams) GetAverageCounterpartyBlockTime() uint64 {
	if m != nil {
		return m.AverageCounterpartyBlockTime
	}
	return 0
}

func (m *CounterpartyChainParams) GetUnbondSlashingValsetsWindow() uint64 {
	if m != nil {
		return m.UnbondSlashingValsetsWindow
	}
	return 0
}

func (m *CounterpartyChainParams) GetCosmosCoinDenom() string {
	if m != nil {
		return m.CosmosCoinDenom
	}
	return ""
}

func (m *CounterpartyChainParams) GetCosmosCoinErc20Contract() string {
	if m != nil {
		return m.CosmosCoinErc20Contract
	}
	return ""
}

func (m *CounterpartyChainParams) GetClaimSlashingEnabled() bool {
	if m != nil {
		return m.ClaimSlashingEnabled
	}
	return false
}

func (m *CounterpartyChainParams) GetBridgeContractStartHeight() uint64 {
	if m != nil {
		return m.BridgeContractStartHeight
	}
	return 0
}

func (m *CounterpartyChainParams) GetValsetReward() types.Coin {
	if m != nil {
		return m.ValsetReward
	}
	return types.Coin{}
}

func init() {
	proto.RegisterType((*Params)(nil), "helios.hyperion.v1.Params")
	proto.RegisterType((*CounterpartyChainParams)(nil), "helios.hyperion.v1.CounterpartyChainParams")
}

func init() { proto.RegisterFile("helios/hyperion/v1/params.proto", fileDescriptor_f5f87689d64baa8c) }

var fileDescriptor_f5f87689d64baa8c = []byte{
	// 841 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x95, 0x4f, 0x6f, 0x1c, 0x35,
	0x18, 0xc6, 0x77, 0x9a, 0x10, 0x1a, 0x6f, 0x42, 0x1a, 0x67, 0xd3, 0x38, 0x7f, 0xd8, 0x1d, 0x15,
	0x09, 0x2d, 0x05, 0x66, 0x92, 0xc0, 0xa9, 0x48, 0x20, 0x76, 0x13, 0xd4, 0x48, 0x1c, 0xd0, 0x06,
	0xa8, 0xc4, 0xc5, 0xf2, 0x8c, 0xdd, 0x19, 0x2b, 0x33, 0xf6, 0xca, 0xf6, 0x6e, 0x94, 0x1b, 0x67,
	0x24, 0x24, 0xbe, 0x03, 0x5f, 0x80, 0x8f, 0xd1, 0x63, 0x8f, 0x08, 0xa1, 0x0a, 0x25, 0x07, 0xbe,
	0x06, 0xb2, 0x3d, 0xb3, 0x3b, 0x9b, 0xb6, 0x52, 0xc4, 0x25, 0xda, 0xf8, 0x79, 0x7e, 0xef, 0x6b,
	0x3d, 0xf6, 0xbc, 0x06, 0xbd, 0x9c, 0x15, 0x5c, 0xea, 0x38, 0xbf, 0x1a, 0x33, 0xc5, 0xa5, 0x88,
	0xa7, 0x47, 0xf1, 0x98, 0x28, 0x52, 0xea, 0x68, 0xac, 0xa4, 0x91, 0x10, 0x7a, 0x43, 0x54, 0x1b,
	0xa2, 0xe9, 0xd1, 0x5e, 0x27, 0x93, 0x99, 0x74, 0x72, 0x6c, 0x7f, 0x79, 0xe7, 0x5e, 0x37, 0x95,
	0xba, 0x94, 0x3a, 0x4e, 0x88, 0x66, 0xf1, 0xf4, 0x28, 0x61, 0x86, 0x1c, 0xc5, 0xa9, 0xe4, 0xa2,
	0xd2, 0x37, 0x49, 0xc9, 0x85, 0x8c, 0xdd, 0x5f, 0xbf, 0xf4, 0xe8, 0xf7, 0x00, 0xac, 0x7c, 0xe7,
	0xba, 0xc1, 0x0c, 0xec, 0xa6, 0x72, 0x22, 0x0c, 0x53, 0x63, 0xa2, 0xcc, 0x15, 0x4e, 0x73, 0xc2,
	0x05, 0xf6, 0x5b, 0x41, 0x41, 0xb8, 0xd4, 0x6f, 0x1f, 0x7f, 0x1c, 0xbd, 0xbe, 0x97, 0x68, 0xd8,
	0x80, 0x86, 0x96, 0xf1, 0xf5, 0x46, 0x3b, 0xe9, 0x9b, 0x05, 0xf8, 0x10, 0xac, 0x10, 0x5a, 0x72,
	0xa1, 0xd1, 0xbd, 0x70, 0xa9, 0xbf, 0x3a, 0xaa, 0xfe, 0x7b, 0x82, 0x7e, 0xfe, 0x3b, 0x6c, 0xfd,
	0xf2, 0xef, 0x1f, 0x8f, 0x37, 0x66, 0x59, 0x78, 0xe2, 0xd1, 0xaf, 0x6d, 0xb0, 0xf3, 0x96, 0x36,
	0xb0, 0x07, 0xda, 0xb5, 0x1d, 0x73, 0x8a, 0x82, 0x30, 0xe8, 0xaf, 0x8e, 0x40, 0xbd, 0x74, 0x46,
	0xe1, 0x21, 0xe8, 0xa4, 0x52, 0x18, 0x45, 0x52, 0x83, 0xb5, 0x9c, 0xa8, 0x94, 0xe1, 0x9c, 0xe8,
	0x1c, 0xdd, 0x73, 0x4e, 0x58, 0x6b, 0xe7, 0x4e, 0x7a, 0x4a, 0x74, 0x0e, 0xbf, 0x04, 0xfb, 0x89,
	0xe2, 0x34, 0x63, 0x78, 0x21, 0x10, 0x42, 0xa9, 0x62, 0x5a, 0xa3, 0x25, 0x07, 0xee, 0x7a, 0x4b,
	0x73, 0x5b, 0x5f, 0x7b, 0x03, 0xfc, 0x10, 0x6c, 0xd4, 0xbc, 0xcb, 0x90, 0x53, 0xb4, 0x1c, 0x06,
	0xfd, 0xe5, 0xd1, 0x7a, 0xc5, 0xd8, 0xd5, 0x33, 0x0a, 0x8f, 0xc1, 0xb6, 0xe6, 0x99, 0x60, 0x14,
	0x4f, 0x49, 0xa1, 0x99, 0xd1, 0xf8, 0x92, 0x0b, 0x2a, 0x2f, 0xd1, 0x3b, 0xce, 0xbd, 0xe5, 0xc5,
	0x1f, 0xbd, 0xf6, 0xcc, 0x49, 0x0d, 0x26, 0x21, 0x26, 0xcd, 0xd9, 0x8c, 0x59, 0x69, 0x32, 0x03,
	0xaf, 0x55, 0xcc, 0x21, 0xe8, 0x54, 0x4c, 0x5a, 0x10, 0x5e, 0xce, 0x90, 0x77, 0x1d, 0x02, 0xbd,
	0x36, 0x74, 0xd2, 0x9c, 0x30, 0x44, 0x65, 0xcc, 0xf8, 0x2e, 0xd8, 0xf0, 0x92, 0xc9, 0x89, 0x41,
	0xf7, 0x3d, 0xe1, 0x35, 0xd7, 0xe4, 0x7b, 0xaf, 0xc0, 0x4f, 0x00, 0x24, 0x53, 0xa6, 0x48, 0xc6,
	0x70, 0x52, 0xc8, 0xf4, 0xc2, 0x21, 0x68, 0xd5, 0xf9, 0x1f, 0x54, 0xca, 0xc0, 0x0a, 0x16, 0x80,
	0xa7, 0xa0, 0x57, 0xbb, 0x17, 0x22, 0x6e, 0xa0, 0xc0, 0xa1, 0x07, 0x95, 0xad, 0x19, 0xf3, 0xbc,
	0xcc, 0x33, 0xb0, 0xad, 0x0b, 0xa2, 0x73, 0xfc, 0xdc, 0x9e, 0xa0, 0xbd, 0x01, 0x3e, 0x48, 0xd4,
	0x0e, 0x83, 0xfe, 0xda, 0xe0, 0x83, 0x17, 0xaf, 0x7a, 0xad, 0xbf, 0x5e, 0xf5, 0xf6, 0xfd, 0x77,
	0xa1, 0xe9, 0x45, 0xc4, 0x65, 0x5c, 0x12, 0x93, 0x47, 0xdf, 0xb2, 0x8c, 0xa4, 0x57, 0x27, 0x2c,
	0x1d, 0x6d, 0xb9, 0x0a, 0xdf, 0x54, 0x05, 0x7c, 0xd8, 0xf0, 0x07, 0xd0, 0xb9, 0x55, 0xd8, 0xe5,
	0x80, 0xd6, 0xee, 0x5e, 0x17, 0x2e, 0xd4, 0x75, 0x59, 0xbd, 0xa1, 0xac, 0x3b, 0x10, 0xb4, 0xfe,
	0x7f, 0xcb, 0xba, 0x43, 0x83, 0x05, 0x08, 0x6f, 0x97, 0x95, 0xe2, 0x79, 0xc1, 0x53, 0xc3, 0x45,
	0x56, 0xb5, 0x78, 0xef, 0xee, 0x2d, 0xde, 0x5f, 0x6c, 0x31, 0x2f, 0xe5, 0xbb, 0x0d, 0x41, 0x77,
	0x22, 0x12, 0x29, 0x28, 0x76, 0x3e, 0xdb, 0xe2, 0xd6, 0xf5, 0xdd, 0x70, 0x47, 0xb7, 0xef, 0x5d,
	0xe7, 0x95, 0x69, 0xf1, 0x1a, 0x5f, 0xbc, 0xb6, 0xe5, 0x84, 0x50, 0xcc, 0x4c, 0x8e, 0xed, 0x6d,
	0x24, 0x66, 0xa2, 0x18, 0x7a, 0x70, 0xf7, 0x2d, 0x1f, 0xdc, 0x0a, 0x9b, 0x9e, 0x9a, 0xfc, 0xbc,
	0x2e, 0x04, 0x1f, 0x83, 0x4d, 0x0f, 0x63, 0x3b, 0x0c, 0x31, 0x65, 0x42, 0x96, 0x68, 0xd3, 0x7d,
	0xc5, 0x1b, 0x5e, 0x18, 0x4a, 0x2e, 0x4e, 0xec, 0x32, 0xfc, 0x02, 0xec, 0x35, 0xbd, 0x4c, 0xa5,
	0xc7, 0x87, 0xb8, 0x9e, 0x11, 0x08, 0x3a, 0x68, 0x67, 0x0e, 0x9d, 0x5a, 0x7d, 0x58, 0xc9, 0xf0,
	0x73, 0xf0, 0xd0, 0xa5, 0x3d, 0x4f, 0x86, 0x09, 0x92, 0x14, 0x8c, 0xa2, 0xad, 0x30, 0xe8, 0xdf,
	0x1f, 0x75, 0x9c, 0x5a, 0x27, 0x72, 0xea, 0x35, 0xf8, 0x15, 0x38, 0x98, 0x8d, 0x9b, 0x7a, 0x4e,
	0x19, 0xa2, 0x0c, 0xce, 0x19, 0xcf, 0x72, 0x83, 0x3a, 0x2e, 0xce, 0xd9, 0xbc, 0xa9, 0xc6, 0x95,
	0x75, 0x3c, 0x75, 0x06, 0x78, 0x02, 0xd6, 0xfd, 0x09, 0x60, 0xc5, 0x2e, 0x89, 0xa2, 0x68, 0x3b,
	0x0c, 0xfa, 0xed, 0xe3, 0xdd, 0xc8, 0xef, 0x33, 0xb2, 0xef, 0x41, 0x54, 0xbd, 0x07, 0x91, 0xdd,
	0xf5, 0x60, 0xd9, 0x86, 0x3a, 0x5a, 0xf3, 0xd4, 0xc8, 0x41, 0x4f, 0x3e, 0xaa, 0xc7, 0x6f, 0x38,
	0x1b, 0xbf, 0x6f, 0x99, 0xb9, 0x83, 0xb3, 0x17, 0xd7, 0xdd, 0xe0, 0xe5, 0x75, 0x37, 0xf8, 0xe7,
	0xba, 0x1b, 0xfc, 0x76, 0xd3, 0x6d, 0xbd, 0xbc, 0xe9, 0xb6, 0xfe, 0xbc, 0xe9, 0xb6, 0x7e, 0x8a,
	0xfd, 0x03, 0xf1, 0x69, 0x2a, 0x15, 0x9b, 0xfd, 0xb6, 0x64, 0x5c, 0x4a, 0x3a, 0x29, 0x58, 0xe3,
	0x9d, 0x33, 0x57, 0x63, 0xa6, 0x93, 0x15, 0xf7, 0x0e, 0x7d, 0xf6, 0x5f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x43, 0x47, 0xad, 0x1b, 0x07, 0x07, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Admins) > 0 {
		for iNdEx := len(m.Admins) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Admins[iNdEx])
			copy(dAtA[i:], m.Admins[iNdEx])
			i = encodeVarintParams(dAtA, i, uint64(len(m.Admins[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.CounterpartyChainParams) > 0 {
		for iNdEx := len(m.CounterpartyChainParams) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CounterpartyChainParams[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *CounterpartyChainParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CounterpartyChainParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CounterpartyChainParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ValsetReward.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0xaa
	if m.BridgeContractStartHeight != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.BridgeContractStartHeight))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa0
	}
	if m.ClaimSlashingEnabled {
		i--
		if m.ClaimSlashingEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x98
	}
	if len(m.CosmosCoinErc20Contract) > 0 {
		i -= len(m.CosmosCoinErc20Contract)
		copy(dAtA[i:], m.CosmosCoinErc20Contract)
		i = encodeVarintParams(dAtA, i, uint64(len(m.CosmosCoinErc20Contract)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x92
	}
	if len(m.CosmosCoinDenom) > 0 {
		i -= len(m.CosmosCoinDenom)
		copy(dAtA[i:], m.CosmosCoinDenom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.CosmosCoinDenom)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x8a
	}
	{
		size := m.SlashFractionBadEthSignature.Size()
		i -= size
		if _, err := m.SlashFractionBadEthSignature.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0x82
	if m.UnbondSlashingValsetsWindow != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.UnbondSlashingValsetsWindow))
		i--
		dAtA[i] = 0x78
	}
	{
		size := m.SlashFractionConflictingClaim.Size()
		i -= size
		if _, err := m.SlashFractionConflictingClaim.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x72
	{
		size := m.SlashFractionClaim.Size()
		i -= size
		if _, err := m.SlashFractionClaim.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x6a
	{
		size := m.SlashFractionBatch.Size()
		i -= size
		if _, err := m.SlashFractionBatch.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x62
	{
		size := m.SlashFractionValset.Size()
		i -= size
		if _, err := m.SlashFractionValset.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x5a
	if m.AverageCounterpartyBlockTime != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.AverageCounterpartyBlockTime))
		i--
		dAtA[i] = 0x50
	}
	if m.AverageBlockTime != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.AverageBlockTime))
		i--
		dAtA[i] = 0x48
	}
	if m.TargetBatchTimeout != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.TargetBatchTimeout))
		i--
		dAtA[i] = 0x40
	}
	if m.SignedClaimsWindow != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.SignedClaimsWindow))
		i--
		dAtA[i] = 0x38
	}
	if m.SignedBatchesWindow != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.SignedBatchesWindow))
		i--
		dAtA[i] = 0x30
	}
	if m.SignedValsetsWindow != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.SignedValsetsWindow))
		i--
		dAtA[i] = 0x28
	}
	if m.BridgeChainId != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.BridgeChainId))
		i--
		dAtA[i] = 0x20
	}
	if len(m.BridgeCounterpartyAddress) > 0 {
		i -= len(m.BridgeCounterpartyAddress)
		copy(dAtA[i:], m.BridgeCounterpartyAddress)
		i = encodeVarintParams(dAtA, i, uint64(len(m.BridgeCounterpartyAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ContractSourceHash) > 0 {
		i -= len(m.ContractSourceHash)
		copy(dAtA[i:], m.ContractSourceHash)
		i = encodeVarintParams(dAtA, i, uint64(len(m.ContractSourceHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.HyperionId) > 0 {
		i -= len(m.HyperionId)
		copy(dAtA[i:], m.HyperionId)
		i = encodeVarintParams(dAtA, i, uint64(len(m.HyperionId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.CounterpartyChainParams) > 0 {
		for _, e := range m.CounterpartyChainParams {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if len(m.Admins) > 0 {
		for _, s := range m.Admins {
			l = len(s)
			n += 1 + l + sovParams(uint64(l))
		}
	}
	return n
}

func (m *CounterpartyChainParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.HyperionId)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.ContractSourceHash)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.BridgeCounterpartyAddress)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.BridgeChainId != 0 {
		n += 1 + sovParams(uint64(m.BridgeChainId))
	}
	if m.SignedValsetsWindow != 0 {
		n += 1 + sovParams(uint64(m.SignedValsetsWindow))
	}
	if m.SignedBatchesWindow != 0 {
		n += 1 + sovParams(uint64(m.SignedBatchesWindow))
	}
	if m.SignedClaimsWindow != 0 {
		n += 1 + sovParams(uint64(m.SignedClaimsWindow))
	}
	if m.TargetBatchTimeout != 0 {
		n += 1 + sovParams(uint64(m.TargetBatchTimeout))
	}
	if m.AverageBlockTime != 0 {
		n += 1 + sovParams(uint64(m.AverageBlockTime))
	}
	if m.AverageCounterpartyBlockTime != 0 {
		n += 1 + sovParams(uint64(m.AverageCounterpartyBlockTime))
	}
	l = m.SlashFractionValset.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.SlashFractionBatch.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.SlashFractionClaim.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.SlashFractionConflictingClaim.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.UnbondSlashingValsetsWindow != 0 {
		n += 1 + sovParams(uint64(m.UnbondSlashingValsetsWindow))
	}
	l = m.SlashFractionBadEthSignature.Size()
	n += 2 + l + sovParams(uint64(l))
	l = len(m.CosmosCoinDenom)
	if l > 0 {
		n += 2 + l + sovParams(uint64(l))
	}
	l = len(m.CosmosCoinErc20Contract)
	if l > 0 {
		n += 2 + l + sovParams(uint64(l))
	}
	if m.ClaimSlashingEnabled {
		n += 3
	}
	if m.BridgeContractStartHeight != 0 {
		n += 2 + sovParams(uint64(m.BridgeContractStartHeight))
	}
	l = m.ValsetReward.Size()
	n += 2 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CounterpartyChainParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CounterpartyChainParams = append(m.CounterpartyChainParams, &CounterpartyChainParams{})
			if err := m.CounterpartyChainParams[len(m.CounterpartyChainParams)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admins", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Admins = append(m.Admins, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CounterpartyChainParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CounterpartyChainParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CounterpartyChainParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HyperionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HyperionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractSourceHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractSourceHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BridgeCounterpartyAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BridgeCounterpartyAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BridgeChainId", wireType)
			}
			m.BridgeChainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BridgeChainId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignedValsetsWindow", wireType)
			}
			m.SignedValsetsWindow = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SignedValsetsWindow |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignedBatchesWindow", wireType)
			}
			m.SignedBatchesWindow = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SignedBatchesWindow |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignedClaimsWindow", wireType)
			}
			m.SignedClaimsWindow = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SignedClaimsWindow |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetBatchTimeout", wireType)
			}
			m.TargetBatchTimeout = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TargetBatchTimeout |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AverageBlockTime", wireType)
			}
			m.AverageBlockTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AverageBlockTime |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AverageCounterpartyBlockTime", wireType)
			}
			m.AverageCounterpartyBlockTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AverageCounterpartyBlockTime |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlashFractionValset", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SlashFractionValset.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlashFractionBatch", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SlashFractionBatch.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlashFractionClaim", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SlashFractionClaim.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlashFractionConflictingClaim", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SlashFractionConflictingClaim.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondSlashingValsetsWindow", wireType)
			}
			m.UnbondSlashingValsetsWindow = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UnbondSlashingValsetsWindow |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlashFractionBadEthSignature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SlashFractionBadEthSignature.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CosmosCoinDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CosmosCoinDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CosmosCoinErc20Contract", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CosmosCoinErc20Contract = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 19:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClaimSlashingEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ClaimSlashingEnabled = bool(v != 0)
		case 20:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BridgeContractStartHeight", wireType)
			}
			m.BridgeContractStartHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BridgeContractStartHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 21:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValsetReward", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ValsetReward.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
