// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: _trading_rpc.proto

/*
Package _trading_rpcpb is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package _trading_rpcpb

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

func request_HeliosTradingRPC_ListTradingStrategies_0(ctx context.Context, marshaler runtime.Marshaler, client HeliosTradingRPCClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq ListTradingStrategiesRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.ListTradingStrategies(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_HeliosTradingRPC_ListTradingStrategies_0(ctx context.Context, marshaler runtime.Marshaler, server HeliosTradingRPCServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq ListTradingStrategiesRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.ListTradingStrategies(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterHeliosTradingRPCHandlerServer registers the http handlers for service HeliosTradingRPC to "mux".
// UnaryRPC     :call HeliosTradingRPCServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterHeliosTradingRPCHandlerFromEndpoint instead.
func RegisterHeliosTradingRPCHandlerServer(ctx context.Context, mux *runtime.ServeMux, server HeliosTradingRPCServer) error {

	mux.Handle("POST", pattern_HeliosTradingRPC_ListTradingStrategies_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/_trading_rpc.HeliosTradingRPC/ListTradingStrategies", runtime.WithHTTPPathPattern("/_trading_rpc.HeliosTradingRPC/ListTradingStrategies"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_HeliosTradingRPC_ListTradingStrategies_0(rctx, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HeliosTradingRPC_ListTradingStrategies_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterHeliosTradingRPCHandlerFromEndpoint is same as RegisterHeliosTradingRPCHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterHeliosTradingRPCHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterHeliosTradingRPCHandler(ctx, mux, conn)
}

// RegisterHeliosTradingRPCHandler registers the http handlers for service HeliosTradingRPC to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterHeliosTradingRPCHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterHeliosTradingRPCHandlerClient(ctx, mux, NewHeliosTradingRPCClient(conn))
}

// RegisterHeliosTradingRPCHandlerClient registers the http handlers for service HeliosTradingRPC
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "HeliosTradingRPCClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "HeliosTradingRPCClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "HeliosTradingRPCClient" to call the correct interceptors.
func RegisterHeliosTradingRPCHandlerClient(ctx context.Context, mux *runtime.ServeMux, client HeliosTradingRPCClient) error {

	mux.Handle("POST", pattern_HeliosTradingRPC_ListTradingStrategies_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req, "/_trading_rpc.HeliosTradingRPC/ListTradingStrategies", runtime.WithHTTPPathPattern("/_trading_rpc.HeliosTradingRPC/ListTradingStrategies"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_HeliosTradingRPC_ListTradingStrategies_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HeliosTradingRPC_ListTradingStrategies_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_HeliosTradingRPC_ListTradingStrategies_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"_trading_rpc.HeliosTradingRPC", "ListTradingStrategies"}, ""))
)

var (
	forward_HeliosTradingRPC_ListTradingStrategies_0 = runtime.ForwardResponseMessage
)
